[workspace]
changelog_config = "cliff.toml"
changelog_update = true
git_tag_enable = true
dependencies_update = false
git_release_enable = false
pr_labels = ["release"]
allow_dirty = false
publish_allow_dirty = false
semver_check = false

[[package]]
name = "tasker-cli"
changelog_include = ["lib-tasker"]
git_release_enable = false
publish = true

[[package]]
name = "lib-tasker"
git_release_enable = false
