[package]
name = "tasker-cli"
version = "1.0.1"
edition = "2021"
authors = ["Dalia Rojas Vallejo <daliarojasvallejo@proton.me>"]
description = "A To-Do CLI application for managing your daily Tasks."
readme = true
repository = "https://github.com/DavoReds/tasker"
license = "GPL-3.0-or-later"
keywords = ["todo", "app", "cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.75"
camino = { version = "1.1.6", features = ["serde1"] }
clap = { version = "4.4.8", features = ["derive"] }
itertools = "0.12.0"
owo-colors = "3.5.0"
serde = { version = "1.0.193", features = ["derive"] }
lib-tasker = { path = "../lib-tasker", version = "0.1.1" }
toml = "0.8.8"
